In [245]:
import numpy as np

In [246]:
def sigmoid(z):
    return 1.0/(1+np.exp(-z))

In [248]:
def sigmoid_derivative(z):
    return z * (1.0-z)

In [262]:
neurns = 4
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], neurns)
        self.weights2 = np.random.rand(neurns, 1)
        self.y = y
        self.output = np.zeros(self.y.shape)
#         print("wights1 {} \n.......\n wights2 {} \n........\n output {}".format(self.wights1, self.wights2, self.output))

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
#         print("layer 1 \n {} \n....\n layer 2 \n{}".format(self.layer1, self.output))
        
    def backprop(self):
        d_w2 = np.dot(self.layer1.T, (2*(self.y - self.output)*sigmoid_derivative(self.output)))
        d_w1 = np.dot(self.input.T,
                            (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output),
                                    self.weights2.T) * sigmoid_derivative(self.layer1)))
        
        self.weights1+=d_w1
        self.weights2+=d_w2

In [263]:
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

In [264]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [265]:
y = np.array([[0],
              [1],
              [1],
              [0]])

In [253]:
y

array([[0],
       [1],
       [1],
       [0]])

In [266]:
NN = NeuralNetwork(X, y)

In [275]:
for _ in range(10000):
    NN.feedforward()
    NN.backprop()

In [276]:
NN.output

array([[0.00552667],
       [0.99426566],
       [0.99343548],
       [0.00659313]])